# Preprocessing 
<!-- will merge with 03 import data section that is already written--> 

## Part One 
<!-- not sure what would be the best name for these headers yet; want to imply the first four are sequential --> 
<!-- need to specify what type of data is being imported -- iEEG recording info) 

<font size="4"> Step #1: Import Signals </font>
<!-- have labeled screenshot for each step similar to the one in 04-preprocessing--> 
Now that you have installed and gotten started with RAVE, you can proceed to importing your iEEG data into the software so that it can be preprocessed and used in future modules.

* **Step 1.1:** Select project & subject

First, use the drop down menu to **specify which project** you want the cleaned subject data to be stored in. If you wish to create a new project, select "New Project" from the drop down menu and indicate your desired project name. Note that by default, this project folder will be created within the `rave_data` folder of the data directory (`data_dir`), in a new folder for your subject. 

Next, use the drop down menu to **select the code for the subject** whose data you want to import. Note that a subject's data should be stored in its own folder within the raw directory (`raw_dir` folder) within the`rave_data` folder. 

Click the **"Create Subject"** button to proceed to the next step. 

* **Step 1.2:** Format & session blocks

RAVE defines a block/session as a period of continuous electrode recording. Here, you should first **select the blocks** that correspond to the trials you want to analyze. 

Note that when you select a block, a preview of the files it contains will pop-up to the right. This feature helps you check that the way you've stored your data is consistent with the file type you've selected. 

Then, **specify the file format** your iEEG data is stored in. RAVE currently supports four file formats: 

* .mat/.h5 file per electrode per block 
* single .mat/.h5 file per block 
* single EDF(+) file per block 
* single BrainVision file 

Note that when you select a format from the drop down, a brief description of the specific format will pop-up underneath the menu. For more information on these file types, visit the Q&A at [Importing Data](#importing-data)

<!-- maybe cross link each of these file formats to a question in the Q&A session so that if someone wants to learn more about a given file format, they can do so without cluttering up this section. or should i give the description right next to the bullet point --> 

* **Step 1.3:** Channel information

RAVE equates a channel to an electrode. Set the following specifications for your channels:  

<!-- this isn't exactly true, so come back later to fix definition --> 

* **Data file:** 

* **Channel numbers:** Indicate the electrodes you wish to analyze. It is recommended that you run the preprocessing steps on all electrodes at once. Note that RAVE can automatically detect potential electrodes based on the specified blocks and file type; this suggestion is displayed at the bottom of the panel. 

* **Physical unit:** Indicate the units you wish to use to measure voltage.

* **Sample rate:** Indicate the rate of your iEEG recording equipment; this value will determine the rate at which the preprocessing will be run.

Now, select the **Validate & Import** button to validate your data. A pop-up will soon appear asking if you are ready to import your data. Please double check all the information you entered is correct, and then select the **Import Data** button to proceed. You will see a progress bar in the bottom left corner. 

<!-- in this paragrraph, make sure to add a note about the skip validate & import button / when it can be used --> 

A pop-up will soon appear indicating that you have successfully imported your subject data into RAVE. You can then proceed to the first preprocessing module, notch filter, for further cleaning of this data. 

<font size="4"> Step #2: Notch Filter </font>
<!-- add very brief description of what this section is for first; essentially it filters out extra noise without disruption to the rest of the signal. it does this by minimizing signals within a narrow bandwith; the rest of the signal is not disrupted because it's not in the bandwidth. a bandwidth is a range of frequencies within a band. a common reason for applying it is because EEG recording setups often include an  --> 

Begin in the **Data Selection** window to specify which data you want to perform the notch filter on. Use the drop down to indicate the desired project and subject. Note that you can press the **Sync from [Import LFP] module** link to automatically select the project and subject that you just imported in the Import Signals module. 

Proceed by selecting the **Load Subject** button. A new screen will load with three panels: 

* **Filter Settings:** Here you can specify configurations for the notch filter. 
* **Inspection:** 
* **Notch: Inspect Signals:** 

Refer to the following screenshot for further guidance. <!-- label purpose of each section --> 
<!-- note: they need to specify the configurations for the notch filter, and then 

<font size="4"> Step #3: Wavelet </font>


<font size="4"> Step #4: Reference Signals </font>


## Part Two

<font size="4"> Surface Registration Localization </font>

## Part Three

<font size="4"> Generate Epoch </font>
