# Supplementary Information

--- 

* The **Q&A section** contains possible questions that may arise when using RAVE and their answers. Note that questions are organized by section. 

* The **3D Viewer section** contains information about the settings on RAVE's 3D viewer, which is used in modules such as Electrode Localization. 

## Q&As 

### RAVE Installation
<!-- note: these are sourced from the troubleshooting section of my documentation, not sure if they're better placed here or in those troubleshooting sections --> 

> **Question:** When updating RAVE, I received a “timeout of 60 seconds was reached” warning message. How do I fix this? 

Answer: Try switching to a faster network connection. 

> **Question:** I already have R and RStudio downloaded. Can I skip the prerequisites? 

Answer: RAVE is dependent on the most recent versions of these applications, so please make sure they are properly updated. Be sure to also review the other pre-requisite steps, like installing Homebrew and the system libraries. The most common reason for issues in the installation of RAVE is failure to properly download these prerequisites. 

> **Question:** How can I check my computer's OS version or CPU type? 

Answer: If using a Mac, this can be found by clicking the apple logo at the top left of the screen, and then clicking "About this Mac". The version and processor (CPU type) will be listed there. 

> **Question:** I received a “the following directories are not writable by your user” error. How do I fix this? 

Answer: If there are multiple accounts on the computer but only one of them has homebrew installed, this error may result. To resolve it, change the ownership of the directories to the current user and make sure this user has write permission.

### External Program Installation (dcm2niix, FreeSurfer, FSL/AFNI)

>Question: When trying to download these external softwares on MacOS, a "cannot be opened because package is from unidentified developer" error message resulted. How do I allow the downloads? 

Answer: Please go to System Preferences > Security & Privacy > General to give the computer permission to download the software. 

### Getting Started with RAVE

> **Question**: I copied a command into the RStudio console, but nothing is happening. What is the issue? 

Make sure to click the red stop sign at the top right of the console to stop the current command. This is necessary to execute a different command. 

> **Question:** I received this message when trying to import a demo subject. 

/Users/aliavyanne/rave_data/raw_dir/YAI (NOT found) /Users/aliavyanne/rave_data/bids_dir//Test/sub-YAI (NOT found)

How do I fix this? 

Answer: Download the demo subject before importing them. Use the following command to download the demo subject YAI: 

```r
rave::download_sample_data("YAI")
```

> **Question:** Where does the demo data come from? 

Answer: The demo data available in RAVE is sourced from experiments run by the Beauchamp Lab at the Perelman School of Medicine, which investigates the neural mechanisms for multisensory integration and visual perception in human subjects. Read more at: https://www.med.upenn.edu/beauchamplab/

### Importing Data

> **Question:** What does the term "channel" refer to? 

Answer: In the early design of RAVE, we focused on exploring one channel per electrode cases, hence we equivalent "channel" to "electrode" here. 

> **Question:** In step 3, why are the "folders" and "electrode" fields designated as "read-only"?

Answer: If these fields are designated as "read only," this means you have already imported the entered subject. To preserve reproducibility, once raw data for a subject is imported and notch filtered, the channel options can not be changed.  

> **Question:** In step 3, what does the term "block" refer to? 

Answer: RAVE defines "block" as a period or session of continuous recording. A block should be named with a zero-padded integer according to the order they were recorded (e.g. 001 for the first session, 002 for the second). 

> **Question:** On the import widgets panel at bottom right, I got a message that electrode files are missing. How do I resolve this? 

Answer: When selecting the "check subject" button, the bottom right panel will indicate if any electrode files are missing based on the electrode numbers you entered in step three. Be sure to double check that the correct electrode numbers in step 3 were indicated.

> **Question:** Does RAVE automatically validate my data? 

Answer: Check for yourself to make sure that each block contains the appropriate files. RAVE will not automatically check this. 

> **Question:** How do I know which file format to select in step 3? 

Answer: When you select a file format from the drop down, RAVE will display brief information on what that format entails and a sample organization for the data directory. Select the format that matches that of the data. 

> **Question:** Where are my inputs and configurations stored for a given subject? 

Answer: This information is stored within `data_dir/<project>/subject>/rave/preprocess/rave.yaml` of the home directory. 

### Notch Filter

> **Question:** What is a Notch Filter? 

Answer: A notch filter blocks a given frequency or a narrow range of frequencies (aka a "bandwidth") from a signal without affecting the rest of that signal. It is often used to minimize line noise interference in raw iEEG data, which helps ensure that future analyses only consider actual brain data. A common source of this interference is the amplifier used in recording set-ups to convert electrode signals into a form readable by the computer. This interference is commonly introduced at 60 Hz, since that is the standard frequency used in the North American electrical grid system. To apply the notch filter, RAVE performs a fast fourier transform (FFT) of the signal.

> **Question:** What is fast fourier transform (FFT)? 

Answer: FFT is an algorithm that can quickly compute the discrete Fourier transform (DFT) of a signal. It transforms the signal from a function of time to the a fucntion of frequency by dividing the signal into its frequency components. Each component constitutes an oscillation with a unique amplitude. This procedure makes it easier to extract a base frequency and its harmonics (e.g. of the amplifier) to perform the notch filter. 

<!-- https://jakevdp.github.io/blog/2013/08/28/understanding-the-fft/, https://www.nti-audio.com/en/support/know-how/fast-fourier-transform-fft#:~:text=The%20%22Fast%20Fourier%20Transform%22%20(,frequency%20information%20about%20the%20signal, http://hyperphysics.phy-astr.gsu.edu/hbase/Math/fft.htmlhttp://hyperphysics.phy-astr.gsu.edu/hbase/Math/fft.html --> 

> **Question:** What is a Welch Periodogram? 

Answer: The Welch method allows for the estimation of the power of a signal at its component frequencies. The time signal is separated into individual blocks, a periodogram is created for each block, and then these periodograms are averaged to estimate the power. The Welch method reduces noise in the power estimation compared to other methods. (Note: a periodogram identifies the dominant frequencies in a time signal.)

> **Question:** How can I switch between subjects while on the notch filter or wavelet modules? 

Answer: In the bottom right corner of the screen, there is a rectangular button that lists the project and subject currently being analyzed -- e.g. "demo/YAD". Click that button to go back to the load data screen and select a different project and/or subject. 

> **Question:** I've already performed the notch filter, but RAVE is not letting me update my channel options. How can I fix this? 

Answer: Once the data is imported and notch filtered, you cannot change the channel options. You should make a new project to change the channel options in this case.

> **Question:** This error popped up when I tried loading a subject into the notch filter module. What do I do? "Found an error while loading the power data: The subject exists but its signal has not been imported yet." 

Answer: Use the menu at left to go back to the "import signals" module. It is necessary to import that subject using the "validate & import" button. 

### Wavelet

> **Question:** What is wavelet decomposition? 

Answer: Wavelet decomposition is a type of time frequency analysis that is used for non-stationary signals (i.e. properties change over time), like that of iEEG. It separates the signal into differing frequency and phase components, which is helpful because signals in the brain are very dynamic. This process makes it so that changes in the signal's power spectra can be visualized across both frequency and time. 

> **Question:** What does wavelet transformation actually entail? 

Answer: A complex wavelet will undergo convulotion with the iEEG signal. The iEEG signal will then be translated across the time axis, using either high frequency or low frequency wavelets. The result is good frequency resolution but poor temporal resolution at low frequencies, and good temporal resolution and poor frequency resolution at high frequencies. Note that a wavelet is created by multiplying a Gaussian function with a sine function. See more: https://sapienlabs.org/lab-talk/time-frequency-analysis-and-wavelets/v

> **Question:** Why can't I down-sample the wavelet coefficients to a sample rate less than or equal to 1? 

> **Question:** How is the power sample rate different from the rate used in the iEEG recording setup? 

Answer: The recording rate is associated with raw voltage data, whereas the power sample rate is associated with time frequency decomposition. 

### Reconstruction & Coregistration

> **Question:** What is the command-line? 

Answer: The computer's command-line is an interface that allows the user to run programs, add/delete files, and use other text-based commands. In the context of surface & registration, RAVE relies on the command-line to run dcm2niix (converts DICOM files to Nifti format), FreeSurfer (allows for the reconstruction of the cortical surface), and FSL home (aligns/overlays the CT image with the MRI data). 

> **Question:** When I press "Check data & command-line tools," I recieve the following warning: "Found existing FreeSurfer reconstructed directory. `recon-all` will ignore the imported T1 images." How do I resolve it? 

Answer: By default, FreeSurfer will continue working on the existing directory. To start from scratch, please manually remove the directory. The warning message will indicate where the directory is located; it will be labeled "fs". E.g. /Users/beauchamplab/rave_data/raw_dir/YCQ/rave-imaging/fs 

> **Question:** When RAVE tries to run the FreeSurfer commands, I recieve the following error in my command-line interface: ERROR: FreeSurfer license file /Applications/freesurfer/7.3.0/.license not found. How do I fix it? 

Answer: A free license file is required to use FreeSurfer. Please refer to the instructions in the installation guide on how to obtain this file and place it in the appropriate place in the file directory: [Install External Programs](#install-external-programs-dcm2niix-freesurfer-fsl-afni).

### Electrode Localization

> **Question:** What is the difference between `MeshPhongMaterial` and `MashLambertMaterial`? 

Answer: MeshPhong and MeshLambert are illumination models used in 3D rendering. MeshPhong computes the lighting of the cortical surface from each pixel, whereas MeshLambert derives the lighting of the brain model from its vertices. 

> **Question:** The brain model shown in the viewer only shows the three planes and not the fully-rendered cortical surface. How do I fix this? 

Answer: To see the full cortical surface on the brain model, it is necessary to use the `-all` flag during the FreeSurfer reconstruction in the Reconstruction & Coregistration module. Please return to this module to re-run the reconstruction. Note that the `-all` flag can take 20 hours to process, so it is recommended to run overnight. 

> **Question:** What is tkrRAS? 

Answer: tkrRAS is a surface coordinate system used by FreeSurfer, where R orients toward the right direction, A orients toward the anterior direction, and S orients toward the superior direction. 

> **Question:** What is MNI152? 

Answer: MNI152 is a volumetric coordinate system derived from averaging 152 individuals' MRI scans.

> **Question:** What is FSLabel? 

Answer: FSLabel represents the anatomical location of the electrode.

> **Question:** What is Neurosynth? 

Answer: Neurosynth is a platform for fMRI data. In the localization plan table, a given electrode's MNI152 coordinates will be hyperlinked here. The link contains data on past maps, studies, and associations that have been associated with the electrode's coordinates.

> **Question:** How do I re-localize an electrode? 

Answer: If edit mode on the 3D viewer is set to CT/Volume, click on the electrode whose position will be changed in the localization plan table. A link will pop-up below the table. Click it, and a white pop-up will appear on the 3D viewer indicating that re-localization mode is active. Simply click on the desired new location for the electrode to adjust the localization. To exit this mode, click the x on the window. If re-localization was requested by mistake, click the link in the white pop-up window. 

## 3D Viewer

This section documents the configurations for RAVE's 3D viewer, used in modules such as Electrode Localization. 

**Default Settings:** 

* <u> Background color: </u> change the background color of the viewer. 

* <u> Record (chrome-on): </u> clicking here will start recording the 3D viewer and clicking again will stop the recording. A video in the .webm format will automatically download to the computer. This feature can be used to generate a video of the localization process. 

* <u> Screenshot: </u> click here to take a screenshot of the current image in the 3D viewer. A .pdf file containing the image will automatically download to the computer. 

* <u> Reset: </u> reset the brain model to its default position.  

* <u> Camera position: </u> use the drop-down to change the view of the brain from the default `free rotate ` (change orientation freely by dragging the cursor) to `[lock]` (preserve current orientation), `right`, `left`, `anterior`, `posterior`, `superior`, or `inferior`.   

* <u> Display coordinates: </u> enabling this checkbox will display the tkRAS coordinate plane in the bottom left corner of the viewer. 

**Volume Settings:** 

These settings control aspects of the view of the 3D model and the CT overlay. 

<!-- add beginning sentence --> 

* <u> Show Panels: </u> Enable this checkbox to simultaneously display the coronal, axial, and sagittal views of the brain. For each viewer, click anywhere on the brain to automatically adjust the other viewers to visualize that position. Clicking the `P` button will lock the viewer so that clicking on the brain will not readjust the other viewers' positions. Note also that the `+` and `-` buttons can be used to zoom in and out of each viewer and the `0` button will reset the zoom back to default. Note that dragging the grey bar at the top of each view box can move the box elsewhere on the panel, and dragging the grey triangle at the bottom right corner will expand the box size. 

* <u> Reset Position: </u> If the Show Panels checkbox is enabled, clicking this button will reset all three plane viewers (coronal, axial, and sagittal) to their default positions. 

* Use <u> Coronal, Axial, and Sagittal </u> sliders to quickly adjust the positions of the planes on the main and individual viewers. Moving the coronal slider from left to right will move that plane from the posterior to anterior end of the brain, respectively. Moving the axial slider from left to right will move that plane from the inferior to superior end of the brain, respectively. Moving the sagittal slider will move that plane from the left to right end of the brain, respectively. For each slider, a coordinte can also be entered manually to set the plane position. By default, each slider is set to 0. Note that keyboard shortcuts are shown in grey next to each slider. 

* <u> Intersect MNI305: </u> displays the coordinates in the MNI305 space where the coronal, axial, and sagittal planes intersect. 

* Use the <u> overlay coronal, axial, and sagittal checkboxes </u> to control whether each plane is visible on the main 3D viewer. By default, these are checked to show all three planes. 

* Use the <u> Distance threshold </u> slider to move selected electrodes above the plane for better viewing, or for demonstrative purposes. It is best to use this feature when the coronal, axial, and sagittal panel views are enabled. By default, this value is set to 2. 

* Use the <u> Voxel Type: </u> drop down menu to select which scan to overlay on the brain model in the 3D viewer. By default, this is set to `CT` indicating that the subject's CT is overlaid in green. 

<!-- control which scan to overlay on the brain model in the 3D viewer. By default, this is set to **CT scan** and the details of the CT are displayed on the viewer in green. whether or not the subject's CT scan is visible on the 3D viewer. By default, this is set to `CT` indicating that the CT is overlaid in **green** on the subject's brain model.  
 -->  

* Use the <u> Voxel Display: </u> drop down menu to control whether or not the selected voxel type (i.e. CT) is visible or hidden on the 3D viewer. By default, it will be set to visible (`normal`). 

* Use the <u> Voxel Opacity: </u> slider to control the opacity of the voxel type selected, from 0 to 1. A value can also be entered manually. By default, this is set to 1. Note that in this case, 0 and 1 will both render the voxels opaque, as 0 disables transparency information. 

* Use the <u> Voxel Min </u> and <u> Voxel Max </u> sliders to adjust the threshold range for how much of the CT scan is visible on the 3D viewer. **Setting this range is important to ensure clear viewing of the electrodes for easy localization -- we want to remove tissues and skeletal substance from the view.** For example, reducing the minimum will display the skull on the 3D viewer. By default, the minimum is set to `3000` and the maximum is set to `3071` as these values provide a clear view of the electrodes with minimum interference from the rest of the CT image. 

Note that the optimal threshold values can vary between subjects. Generally, a higher threshold may be required if electrodes are near the surface, and a lower threshold can help with electrodes deep in the brain. 

**Surface Settings:** 

These settings control aspects of the 3D model of the subject's cortical surface. Note that if a subject's cortical surface was not reconstructed yet (such as when using the Electrode Localization module), these settings can be ignored. 

* Use the <u> Subject: </u> drop-down menu to easily switch between which subject's 3D brain model is displayed in the 3D viewer. 

* Use the <u> Surface Type: </u> drop down menu to switch the surface being viewed. Options include `pial` (gray matter), `white matter` only, `sulcus`, and `subcortical structures`.

* Use the <u> Surface Material: </u> drop down menu to select a material to visualize the subject's cortical surface. The materials, `MeshPhong` (default) and `MeshLambert`, differ in how they display lighting of the 3D brain model. 

* Use the <u> Left Hemisphere: </u> and <u> Right Hemisphere: </u> drop-down menus to set the visualization of each hemisphere as `normal` (complete, solid representation of cortical surface), `wireframe` (simplified, skeletal representation of cortical surface using lines), or `hidden` (hemisphere not displayed). By default, each hemisphere is set to `normal.` 

* Use the <u> Left Opacity: </u> and <u> Right Opacity: </u> sliders to control the opacity of each hemisphere, from 0 (hemisphere not displayed) to 1 (hemisphere fully-rendered). Note that a value can also be entered manually. By default, each slider is set to 1. 

* Use the <u> Surface Color: </u> drop-down menu to control how the color of the 3D brain model is rendered. By default, this is set to `vertices,` where color will be given to each vertice of the triangular shapes that make up the model. Another option is `sync from voxels` (note that selecting this will open two sliders for the `blend factor` and `sigma`, set to 0.4 and 3 by default). This is helpful when using the surface to show volume, like for grey matter. Another option is `sync from electrodes` (note that in addition to blend factor and sigma, a `decay` slider will also be displayed, set to 0.15 by default). Each electrode radiates light on the brain model; this is useful to cluster electrodes by different functions. The last option is `none` (no color rendering on model).

**Electrodes:** 

* The <u> Map Electrodes: </u> checkbox controls whether or not electrodes are mapped to the brain surface. By default, this is unchecked. If the box is checked, a `surface mapping` drop-down menu will appear to select the surface to map the electrodes to (options: std.141, mni305, or no mapping) and `volume mapping` to alternatively select the volume to display the electrodes in if surface mapping isn't used (options: mni305 or no mapping). Enabling this feature is helpful when mapping electrodes for more than 1 subject, so that all electrodes from multiple subjects can be visualized on the same coordinate system using a template brain. 

* Use the <u> Visibility: </u> drop-down menu to control which localized electrodes are visible in the 3D viewer. The default setting is `all visible`, meaning all of a subject's electrodes are shown on the viewer. `Hide inactives` will hide electrodes from groups that aren't currently being worked on. `Hidden` will hide all electrodes.  

**Electrode Localization:** 

* By default, the <u> Edit mode </u> drop-down menu is set to `disabled.` Change edit mode to `CT/volume` (have CT scan) or `MRI Slice` (no CT scan) when ready to localize electrodes. Use `refine` if electrodes have already been localized and small changes are just being made to placements. 

> Note: When `refine` mode is selected, three new buttons will appear: `Auto-Adjust All`, which can be used to automatically adjust the coordinates for the electrodes in a group to better fit their positions on the 3D viewer. If certain electrodes in the group were selected in refine mode (shown in red), click `Auto-Adjust` highlighted to  automatically re-adjust just the selected electrodes. Click `Reset Highlighted` to de-select all red electrodes in the group.  

* Use the <u> Electrode scale: </u> slider to control the size of the yellow circles that represent localized electrodes. Use the <u> Text scale </u> slider to control the size of the numbers used to label each circle. 

<!-- 
* Use the <u> Enable/Disable Electrodes </u> feature to render selected electrodes active or inactive. --> 

* When hovering over or localizing an electrode in the 3D viewer, the <u> tkrRAS, MNI305, and T1 RAS </u> locations will automatically be shown in these fields. 

* Use the <u> Interpolate Size: </u> field to quickly localize electrodes by inputting the total number of electrodes - 2 for the current group, if the first and last electrode in the group have already been localized. Then, press <u> Interpolate from Recently Added </u> to have RAVE automatically localize the remaining electrodes in the group. 

<!-- clarify that they have to be in a line? --> 

* Use the <u> Download as CSV: </u> button to download a .csv file for the group whose electrodes are currently being localized. The file will contain coordinates and FsLabels for each electrode in the group, similar to the information shown in the table on Localization Plan Details panel.  

**Data Visualization:** 

* Enable the <u> Highlight Box </u> checkbox to automatically add a red box around a currently selected electrode. This box can help with viewing an electrode against the brain surface, or for demonstrative purposes. 

* Enable the <u> Info Text </u> checkbox to label the 3D viewer in the top-right corner with the subject ID, as well as the currently selected electrode's label and MNI305 coordinates. This can be helpful for demonstrative purposes.

> Note: To view keyboard shortcuts for all of these settings, visit [the RAVE Github repository](https://github.com/dipterix/threeBrain/blob/master/shortcuts.md#3d-brain-viewer-shortcuts)